# Generated by Django 5.1.1 on 2024-09-16 00:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='recipes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('link', models.URLField(blank=True)),
                ('cooktime', models.CharField(max_length=45)),
                ('calories', models.CharField(max_length=20)),
                ('servingSize', models.CharField(max_length=20)),
                ('carbs', models.CharField(max_length=45)),
                ('fats', models.CharField(max_length=45)),
                ('proteines', models.CharField(max_length=45)),
                ('description', models.TextField(blank=True)),
                ('directions', models.TextField(blank=True)),
                ('insertDate', models.DateField(blank=True)),
                ('imageLink', models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='ingridient',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('ingridient', models.CharField(max_length=80)),
                ('idRecipes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ingridients.recipes')),
            ],
        ),
        migrations.CreateModel(
            name='searchIngridients',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('ingridient', models.CharField(max_length=80)),
                ('idRecipes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ingridients.recipes')),
            ],
        ),
    ]
