# Generated by Django 5.1.1 on 2024-09-16 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingridients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipes',
            name='calories',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='recipes',
            name='carbs',
            field=models.CharField(max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='recipes',
            name='cooktime',
            field=models.CharField(max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='recipes',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='recipes',
            name='directions',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='recipes',
            name='fats',
            field=models.CharField(max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='recipes',
            name='imageLink',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='recipes',
            name='insertDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='recipes',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='recipes',
            name='proteines',
            field=models.CharField(max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='recipes',
            name='servingSize',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
