# Generated by Django 5.1.1 on 2024-09-16 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingridients', '0002_alter_recipes_calories_alter_recipes_carbs_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingridient',
            name='id',
            field=models.UUIDField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='recipes',
            name='id',
            field=models.UUIDField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='searchingridients',
            name='id',
            field=models.UUIDField(primary_key=True, serialize=False, unique=True),
        ),
    ]
