# Generated by Django 5.1.1 on 2024-09-16 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingridients', '0003_alter_ingridient_id_alter_recipes_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingridient',
            name='id',
            field=models.CharField(max_length=80, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='recipes',
            name='id',
            field=models.CharField(max_length=80, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='searchingridients',
            name='id',
            field=models.CharField(max_length=80, primary_key=True, serialize=False, unique=True),
        ),
    ]
