# Generated by Django 5.1.1 on 2024-09-23 03:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ingridients', '0004_alter_ingridient_id_alter_recipes_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingridient',
            old_name='idRecipes',
            new_name='recipes',
        ),
        migrations.RenameField(
            model_name='searchingridients',
            old_name='idRecipes',
            new_name='recipes',
        ),
    ]
