# Generated by Django 5.1.1 on 2024-09-23 03:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingridients', '0005_rename_idrecipes_ingridient_recipes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingridient',
            name='recipes',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe_ing', to='ingridients.recipes'),
        ),
    ]
